version: "3.3"
services:
  api: 
    build: API
  site: 
    build: SITE
  proxy:
    build: PROXY
    ports:
      - "80:80"
    links:
      - api
      - site
    depends_on:
      - site
      - api